### ISSUE TITLE
Playarrow does not start another room

### ISSUE THREAD

**Issue by oliverhausler** [attach-live/attach-chat-starter#7]
playarrow does not start another room, when the secret is changed **after** the user is in a room already.

![image](https://cloud.githubusercontent.com/assets/8090341/24877238/61050582-1de3-11e7-99d2-815b3a10a50e.png)

**Comment by oliverhausler** [comment]
@dodekeract I assigned this to @lnogol, so he can fix it together with https://github.com/attach-live/attach-chat-starter/issues/8

**Comment by lnogol** [comment]
seems to be working now

**Comment by oliverhausler** [comment]
@lnogol It starts a room, but when it is clicked again, it does not start a new room.

Try this:

1. enter a secret
2. start room A
3. enter another secret
4. start room B

We're still in room A.

You can test by using 2 browser tabs. Same secret == same room, you must see 2 users then.

I assigned this to myself, as there are more changes. Will assign back to you later so you can do everything at once, but Florian needs to finish the SDK before we can work on this.

**Comment by oliverhausler** [comment]
Transferred to https://github.com/attach-live/attach-chat-starter-setup/issues/5
