### ISSUE TITLE
Old avatar when room is started before upload has finished

### ISSUE THREAD

**Issue by oliverhausler** [attach-live/attach-chat-starter#8]
We must hide the start arrow in 4., while an upload is in progress. Otherwise we'll see the previous avatar in video unit, when it is invoked, while still uploading.

**Comment by oliverhausler** [comment]
@lnogol I would say let's finish playground first, so we can test there. Then fix there and transfer here.

**Comment by dodekeract** [comment]
Fixed by b1e2bc927f2e275b8258296ca88b91885947e82e.
