### ISSUE TITLE
Add progress indicator

### ISSUE THREAD

**Issue by oliverhausler** [attach-live/attach-chat-starter#9]
The upload takes too long since we added image compression. I wouldn't want to fix this now, but please add a progress indicator.

**Comment by lnogol** [comment]
the code right now is a nice one-liner `fetch(url, options).then(...)` using the `fetch` polyfill. however, it doesn't expose / let the caller access the `XMLHttpRequest` object which has a `progress` event that can be used for this (show an indicator, change cursor etc)

this one line would turn into something like [this](https://github.com/github/fetch/issues/89#issuecomment-256610849)

**Comment by oliverhausler** [comment]
@lnogol Then leave it out please. When you're done, let me know so I can look at it, and then we should push to production and test again.
